<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Atribuir Teste</title>

        <!-- Bootstrap / CSS -->
        <link rel="stylesheet" href="/styles/custom-atribuir-realizar-teste.css">

    </head>
    <body>
        
        <!--Header-->
        <nav class="navbar navbar-expand-lg navbar-dark" id="header">
            <div class="container-fluid background-navbar">
                
                <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <img src="/images/global/navbar-button.svg" class="navbar-button">
                </button>

                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="#">Home</a>
                        <a class="nav-link" href="#">Funcionário</a>
                        <a class="nav-link" href="#">Candidatos</a>
                        <a class="nav-link" href="#">Requisições</a>
                        <a class="nav-link" href="#">Vagas</a>
                        <a class="nav-link" href="#">Processos Seletivos</a>
                        <a class="nav-link active" href="#">Testes</a>
                        <a class="nav-link" href="#">Entrevistas</a>
                        <a class="nav-link" href="#">Suporte</a>
                        <a class="nav-link" href="#">Sair</a>
                    </div>
                </div>
            </div>
        </nav>

        <form action="/cadastrar_teste" method="post">
            <div class="container">
                <div class="title">
                    <h1 class="title-1 mb-4">Atribuir Teste</h1>
                </div>

                <div class="row mb-3">
                    <label for="test_Title" class="col-sm-2 form-label form-label-t-test">Título do Teste</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control digitar-titulo" name="test_Title">
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="description" class="form-label">Descrição</label>
                    <div class="col-sm-12 mb-3">
                        <textarea type="text" class="form-control text-area" name="description"></textarea>
                    </div>
                </div>

                <hr />

                <div class="title"> 
                    <h2 class="title-2">Perguntas</h2>
                    <!-- <img src="../../../../Public/images/global/info.svg"> -->
                    <img src="/images/global/info.svg">
                </div>

                <div class="questions" id="questions">
                    <div id="question_1">  
                        <div class="title">
                            <h2 class="title-2">1. <img src="/images/global/edit.svg" alt="edit" ></h2>            
                        </div>
        
                        <div class="row mb-3">
                            <label class="form-label">Título da Pergunta</label>
                            <div class="col-sm-12">
                                <textarea type="text" class="form-control text-area titulo" name="question_title_1"></textarea>
                            </div>
                        </div>
                        
                        <div class="title">
                            <h2 class="title-2">Respostas</h2>            
                        </div>

                        <div class="mb-3">
                            <label class="letra">A)</label>
                            <textarea type="text" class="form-control text-area" name="quest_1_answer_1"></textarea>
                            <label>Resposta Correta:</label>
                            <label class="switch">
                                <input type="checkbox" name="check_quest_1_answer_1">
                                <span class="slider round"></span>
                            </label>
                        </div> 

                        <div class="mb-3">
                            <label class="letra">B)</label>
                            <textarea type="text" class="form-control text-area" name="quest_1_answer_2"></textarea>
                            <label>Resposta Correta: </label>
                            <label class="switch">
                                <input type="checkbox" name="check_quest_1_answer_2">
                                <span class="slider round"></span>
                            </label>
                        </div> 

                        <div class="mb-3">
                            <label class="letra">C)</label>
                            <textarea type="text" class="form-control text-area" name="quest_1_answer_3"></textarea>
                            <label>Resposta Correta: </label>
                            <label class="switch">
                                <input type="checkbox" name="check_quest_1_answer_3">
                                <span class="slider round"></span>
                            </label>
                        </div>

                        <div class="mb-3">
                            <label class="letra">D)</label>
                            <textarea type="text" class="form-control text-area" name="quest_1_answer_4"></textarea>
                            <label>Resposta Correta: </label>
                            <label class="switch">
                                <input type="checkbox" name="check_quest_1_answer_4">
                                <span class="slider round"></span>
                            </label>
                        </div>
                    </div>  
                    <div id="btn-area-form-0" class="btn-area-form">
                        <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addPergunta()">
                        <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removePergunta()">
                    </div>
                </div>
                <div class="buttons">
                    <a href="/processo_seletivo" class="btn btn-outline-primary mb-5">Voltar</a>
                    <button type="submit" class="btn btn-outline-primary mb-5">Atribuir</button>
                </div>
            </div>
        </form>

        <!--Footer-->
        <footer class="footer">
            <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
            <img src="/images/global/facebook.svg" class="img-footer" onclick="">
            <img src="/images/global/email.svg" class="img-footer" onclick="">
            <label class="label-footer">+55 (15) 5555-5555</label>
        </footer>

        <!--Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

        <!-- <script src="../../../../Public/scripts/employee-scripts/atribuir-teste.js"></script> -->
        <script src="/scripts/employee-scripts/atribuir-teste.js"></script>
    </body>
</html>