<!doctype html>
<html lang="pt-BR">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="../../../../Public/styles/custom-entrevistas-registradas.css">

    <title>Entrevistas Registradas</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="../../../../Public/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="../../../../Public/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    <a class="nav-link" href="#">Gestor</a>
                    <a class="nav-link" href="#">Gerar Vaga</a>
                    <a class="nav-link" href="#">Requisições</a>
                    <a class="nav-link" href="#">Vagas</a>
                    <a class="nav-link" href="#">Sobre</a>
                    <a class="nav-link" href="#">Suporte</a>
                    <a class="nav-link" href="#">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Body-->
    <div class="principal" id="body">

        <div class="title">
            <h1 class="title-1">Entrevistas Registradas</h1>
        </div>
        <br>

        <div class="row mb-2">
            <label for="colFormLabel" class="label">Candidato</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="Candidato" name="Candidato">
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-2">
            <label for="colFormLabel" class="label">Cargo</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="Cargo" name="cargo">
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>
        <br>

        <a href="../candidatescreens/perfil.html"><input name="AreaCand"
        type="button" value="Área do Candidato" class="AreaCand"></a>
        <br><br><br>

        <h3 class="title-2">Estilo Comportamental</h3>
        <textarea name="DescrEstilo" cols="50" rows="8" id="DescrEstilo" value=""
        input="" class="textarea" readonly></textarea>
        <br>

        <h3 class="title-2">Pontos Positivos</h3>
        <textarea name="DescrPositivo" cols="50" rows="8" id="DescrPositivo" value=""
        input="" class="textarea" readonly></textarea>
        <br>

        <h3 class="title-2">Pontos Negativos</h3>
        <textarea name="DescrNegativo" cols="50" rows="8" id="DescrNegativo" value=""
        input="" class="textarea" readonly></textarea>
        <br><br>

        <center>
            <a href="./gerenciar-entrevista.html"><input name="Voltar" type="button"
            value="Voltar" class="Voltar"></a>
        </center>
    </div>

        <!--Footer-->
        <footer class="footer">
            <img src="../../../../Public/images/global/linkedin.svg" class="img-footer" onclick="">
            <img src="../../../../Public/images/global/facebook.svg" class="img-footer" onclick="">
            <img src="../../../../Public/images/global/email.svg" class="img-footer" onclick="">
            <label class="label-footer">+55 (15) 5555-5555</label>
        </footer>

        <!--Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
            crossorigin="anonymous"></script>
</body>

</html>