<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Marcar Entrevista</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-marcar-entrevista.css">

</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    <a class="nav-link" href="#">Gestor</a>
                    <a class="nav-link" href="#">Gerar Vaga</a>
                    <a class="nav-link" href="#">Requisições</a>
                    <a class="nav-link" href="#">Vagas</a>
                    <a class="nav-link" href="#">Sobre</a>
                    <a class="nav-link" href="#">Suporte</a>
                    <a class="nav-link" href="#">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <?php
    if (isset($_GET['entrevistaMarcar'])) {
    ?>

        <script>
            alert("Entrevista Salva com Sucesso!");
        </script>

    <?php
    } 
    ?>

    <form action="/entrevista_candidato_marcar" method="post">
        <div class="container">
            <div class="title">
                <h1 class="title-1">Marcar Entrevista</h1>
            </div>

            <!--Pesquisa-->
            <div class="row">
                <label class="label1">Título</label>

                <input type="text" class="form-control" name="titulo">
            </div>

            <div class="row">
                <label class="label1">Descrição</label>

                <textarea type="text" class="form-control" id="textarea" rows="3" name="desc"></textarea>
            </div>

            <div class="row">
                <label for="sdate" class="label1">Data</label>

                <input type="date" class="form-control" name="date">
            </div>

            <div class="row">
                <label for="hora" class="label1">Hora</label>
                
                <input type="time" class="form-control" name="hora">
            </div>

            <div class="row">
                <label class="label2">Candidato</label>

                <select class="form-select" aria-label="nome-candidato" name="nome-candidato">
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>

            <div class="row">
                <label class="label2">Responsável</label>

                <select class="form-select" aria-label="resp" name="resp">
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>

                
            <div class="row">
                <label class="label2">Processo Seletivo</label>

                <select class="form-select" aria-label="processo-seletivo" name="processo-seletivo">
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>

            <hr>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                <button type="submit" class="btn btn-outline-primary mb-5">Marcar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>


    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/manager-scripts/marcar-entrevista.js"></script>
</body>

</html>