<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gerenciar Entrevistas</title>

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-gerenciar-entrevista.css">

</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    <a class="nav-link" href="#">Gestor</a>
                    <a class="nav-link" href="#">Gerar Vaga</a>
                    <a class="nav-link" href="#">Requisições</a>
                    <a class="nav-link" href="#">Vagas</a>
                    <a class="nav-link" href="#">Sobre</a>
                    <a class="nav-link" href="#">Suporte</a>
                    <a class="nav-link" href="#">Sair</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="title">
            <h1 class="title-1">Gerenciar Entrevistas</h1>
        </div>

        <!--Pesquisa-->
        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Processo Seletivo</label>
            <div class="col-sm-10">
                <select class="col form-select" aria-label="processo-seletivo" name="processo-seletivo">
                    <option selected></option>
                    <option value="1">#</option>
                    <option value="2">#</option>
                    <option value="3">#</option>
                </select>
            </div>
        </div>

        <div class="row mb-3">
            <label for="colFormLabel" class="col-sm-2 form-label">Organizar por</label>

            <select class="col-sm-10 form-select" aria-label="organizar-por" name="organizar-por">
                <option selected>#</option>
                <option value="1">#</option>
            </select>
        </div>

        <div class="btn-search">
            <button type="button" class="btn btn-outline-primary mb-5">Registradas</button>
            <button type="button" class="btn btn-outline-primary mb-5">Não Registradas</button>
        </div>

        <hr>

        <!--resultado-->
        <div class="bottom-area">
            <div class="candidato">
                <div class="card">
                    <div class="card-img"></div>

                    <div class="card-body">
                        <h4 class="card-title" id="nome-candidato">Nome do Candidato</h4>
                        <p class="card-text title-user" id="hora-entrevista">Hora de Entrevista</p>
                        <p class="card-text" id="data-entrevista">Data de Entrevista</p>
                    </div>
                </div>

                <button type="button" class="btn btn-outline-primary mb-4">Visualizar</button>
            </div>
        </div>

        <hr>

        <!--Resposta-->
        <?php foreach($this->view->todasEntrevistasCandidato as $key => $entrevistaCandidato) {?>
        <form action="/visualizar_entrevista_candidato" method="post">
            <div class="candidato">
                <div class="card">
                    <div class="card-img"></div>

                    <div class="card-body">
                        <!-- <h4 class="card-title">Departamento: <?= $entrevistaCandidato->nome_departamento ?> </h4> -->
                        <h4 class="card-title" id="nome-candidato">
                            <?= $entrevistaCandidato->id_user ?>
                        </h4>
                        <p class="card-text title-user" id="hora-entrevista">
                            <?= $entrevistaCandidato->hora_entrevista ?>
                        </p>
                        <p class="card-text" id="data-entrevista">
                            <?= $entrevistaCandidato->data_entrevista ?>
                        </p>
                    </div>
                </div>
                <!-- <button type="button" class="btn btn-outline-primary mb-4">Divulgar</button> -->
                <button type="submit" class="btn btn-outline-primary mb-4">Visualizar</button>
                <input type="hidden" name="id_entrevista" value="<?= $entrevistaCandidato->id_entrevista ?>">
            </div>
        </form>
        <?php } ?>

        <div class="buttons">
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = 'http://localhost:3000/entrevista-marcar'">Marcar</button>
            <button type="button" class="btn btn-outline-primary mb-5"
                onclick="window.location.href = 'http://localhost:3000/home'">Voltar</button>
        </div>

    </div>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>


    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src=""></script>
</body>

</html>