<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualizar Processo Seletivo</title>

    <!-- Bootstrap / CSS -->
    <!--<link rel="stylesheet" href="../../../../Public/styles/custom-cadastrar-processo-seletivo.css">-->
    <link rel="stylesheet" href="/styles/custom-cadastrar-processo-seletivo.css">
    <link rel="stylesheet" href="/styles/custom-vagas-candidatadas.css">
    
</head>

<body>

    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <!--<a class="navbar-brand" href="#"><img src="../../../../Public/images/global/logo.svg" alt=""></a>-->
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <!--<img src="../../../../Public/images/global/navbar-button.svg" class="navbar-button">-->
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    <a class="nav-link" href="#">Gestor</a>
                    <a class="nav-link" href="#">Gerar Vaga</a>
                    <a class="nav-link" href="#">Requisições</a>
                    <a class="nav-link" href="#">Vagas</a>
                    <a class="nav-link" href="#">Sobre</a>
                    <a class="nav-link" href="#">Suporte</a>
                    <a class="nav-link" href="#">Sair</a>
                </div>
            </div>
    </nav>

    <form action="/processo_seletivo_cadastrar" method="post">
        <div class="container">
            <div class="title">
                <h1 class="title-1">Processo Seletivo</h1>
            </div>

            <div class="title">
                <h2 class="title-2">Dados de Cadastro</h2>
                <!-- <img src="../../../../Public/images/global/info.svg"> -->
                <img src="/images/global/info.svg">
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título do Processo Seletivo</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" value="<?= $this->view->detalhesProcessoSeletivo->titulo_proc ?>" placeholder="" name="tituloProcSeletivo">
                </div>
            </div>
            <div class="row mb-3">
                <label for="vacancy" class="col-sm-2 form-label form-label">Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" value=""  name="vacancy">
                </div>
            </div>
            <div class="row mb-3">
                <label for="responsible" class="col-sm-2 form-label form-label">Responsável</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="colFormLabel" value="<?= $this->view->detalhesProcessoSeletivo->nome ?>" name="responsible">  
                </div>
            </div>

            <div class="title">
                <h2 class="title-2">Dados do Processo</h2>
                <!-- <img src="../../../../Public/images/global/info.svg"> -->
                <img src="/images/global/info.svg">
            </div>

            <?php 
                $status = $this->view->detalhesProcessoSeletivo->status_proc;
            ?>

            <div class="row mb-3 vagas">
                <!--6%-->
                    <div class="title">
                        <h2 class="title-2">Status</h2>
                    </div>

                <div class="mb-3 vaga" id="1-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-6" per="6%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberto</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Divulgado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Testes</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevistas</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizado</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--24%-->
                <div class="mb-3 vaga" id="2-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-24" per="24%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberto</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Divulgado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Testes</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevistas</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizado</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--59%-->
                <div class="mb-3 vaga" id="3-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-59" per="59%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberto</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Divulgado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Testes</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevistas</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizado</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--77%-->
                <div class="vaga" id="4-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-77" per="77%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberto</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Divulgado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Testes</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevistas</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizado</span>
                            <img src="">
                        </div>
                    </div>

                </div>

                <!--100%-->
                <div class="vaga" id="5-etapa">
                    <div class="vaga-bar">
                        <div class="vaga-per-100" per="100%"></div>
                    </div>

                    <div class="mb-3 texts">
                        <div class="text-box">
                            <span>Aberto</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Divulgado</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Testes</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Entrevistas</span>
                            <img src="">
                        </div>

                        <div class="text-box">
                            <span>Finalizado</span>
                            <img src="">
                        </div>
                    </div>

                </div>
            </div>                    

            <div class="row mb-3">
                <label for="start_date" class="col-sm-2 form-label form-label">Data de Início</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" value="<?= $this->view->detalhesProcessoSeletivo->data_inicio ?>" name="start_date">
                </div>
                <div class="row mb-3">
                    <label for="end_date" class="col-sm-2 form-label form-label">Data de Término</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" value="<?= $this->view->detalhesProcessoSeletivo->data_termino ?>" name="end_date">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Regra de Classificação</label>
                    <div class="col-sm-10">
                        <input type="number" class="form-control" id="colFormLabel" value="<?= $this->view->detalhesProcessoSeletivo->regra_class ?>" name="classification-rule" min="0" step="0.1" max="1">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="teste_Title" class="col-sm-2 form-label form-label">Descrição</label>
                    <textarea type="text" class="form-control text-area" name="descProc"><?=$this->view->detalhesProcessoSeletivo->descricao ?></textarea>
                </div>
            </div>

            <button id="btnLiberarTeste" type="button" class="btn btn-outline-primary mb-5">Liberar Teste</button>

            <hr/>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                <button type="submit" class="btn btn-outline-primary mb-5">Cadastrar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <!-- <img src="../../../../Public/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="../../../../Public/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="../../../../Public/images/global/email.svg" class="img-footer" onclick=""> -->
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>
</body>

</html>

<script language="javascript">
    var status = "<?php print $status; ?>";
                
    document.getElementById('1-etapa').style.display = 'none';
    document.getElementById('2-etapa').style.display = 'none';
    document.getElementById('3-etapa').style.display = 'none';
    document.getElementById('4-etapa').style.display = 'none';
    document.getElementById('5-etapa').style.display = 'none';

    if(status == "Aberto")
        document.getElementById('1-etapa').style.display = 'block'; 
    else if(status == 'Divulgado')
        document.getElementById('2-etapa').style.display = 'block'; 
    else if(status == 'Testes')
        document.getElementById('3-etapa').style.display = 'block'; 
    else if(status == 'Entrevistas')
        document.getElementById('4-etapa').style.display = 'block'; 
    else
        document.getElementById('5-etapa').style.display = 'block'; 


    var btn = document.getElementById('btnLiberarTeste');

    btn.disabled = true;

    if(status == "Divulgado")
        btn.disabled = false;
    else    
        btn.disabled = true;
</script>