<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registrar Entrevista</title>

        <!-- Bootstrap / CSS -->
        <link rel="stylesheet" href="/styles/custom-registrar-entrevista.css">
    </head>
    <body>
        
        <!--Header-->
        <nav class="navbar navbar-expand-lg navbar-dark" id="header">
            <div class="container-fluid background-navbar">
                <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <img src="/images/global/navbar-button.svg" class="navbar-button">
                </button>

                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="#">Home</a>
                        <a class="nav-link" href="#">Funcionário</a>
                        <a class="nav-link" href="#">Candidatos</a>
                        <a class="nav-link" href="#">Requisições</a>
                        <a class="nav-link" href="#">Vagas</a>
                        <a class="nav-link" href="#">Processos Seletivos</a>
                        <a class="nav-link" href="#">Testes</a>
                        <a class="nav-link active" href="#">Entrevistas</a>
                        <a class="nav-link" href="#">Suporte</a>
                        <a class="nav-link" href="#">Sair</a>
                    </div>
                </div>
            </div>
        </nav>

        <?php
        if (isset($_GET['entrevistaRegistrar'])) {
        ?>
    
            <script>
                alert("Registro da Entrevista Realizado com Sucesso!");
            </script>
    
        <?php
        }
        ?>
        
        <form action="entrevista_candidato_registrar" method="post">
            <div class="container">
                <div class="title">
                    <h1 class="title-1">Registrar Entrevista</h1>
                    <img class="icon-click" src="/images/global/info.svg">
                </div>

                <div class="row mb-3">
                    <label for="colFormLabel" class="colsm-2 form-label label">Responsável</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control form" id="colFormLabel" readonly placeholder="" name="resp">
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="role" class="col-sm-2 form-label label">Processo Seletivo</label>
                    <div class="col-sm-10">
                        <select class="col form-select" name="role">
                            <option selected></option>
                            <option value="1">#</option>
                            <option value="2">#</option>
                            <option value="3">#</option>
                        </select>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="applpicant" class="col-sm-2 form-label label">Candidato</label>
                    <div class="col-sm-10">
                        <select class="col form-select" name="applpicant">
                            <option selected></option>
                            <option value="1">#</option>
                            <option value="2">#</option>
                            <option value="3">#</option>
                        </select>
                    </div>
                </div>

                <hr />

                <div>
                    <div class="title">
                        <h2 class="title-2">Estilo Comportamental <img class="icon" src="/images/global/edit.svg" alt="edit"></h2>            
                    </div>
                    <div class="col-sm-12 mb-3">
                        <textarea type="text" class="form-control text-area" name="behavioral_style"></textarea>
                    </div>
                </div>

                <div>
                    <div class="title">
                        <h2 class="title-2">Pontos Positivos <img class="icon" src="/images/global/edit.svg" alt="edit"></h2>            
                    </div>
                    <div class="col-sm-12 mb-3">
                        <textarea type="text" class="form-control text-area" name="positive_points"></textarea>
                    </div>
                </div>
                
                <div>
                    <div class="title">
                        <h2 class="title-2">Pontos Negativos <img class="icon" src="/images/global/edit.svg" alt="edit"></h2>            
                    </div>
                    <div class="col-sm-12 mb-3">
                        <textarea type="text" class="form-control text-area" name="negative_points"></textarea>
                    </div>
                </div>
                
                <div class="buttons">
                    <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                    <button type="submit" class="btn btn-outline-primary mb-5">Registrar</button>
                </div>
            </div>
        </form>

        <!--Footer-->
        <footer class="footer">
            <a href="">
                <img src="/images/global/linkedin.svg" class="img-footer">
            </a>
            <a href="">
                <img src="/images/global/facebook.svg" class="img-footer">
            </a>
            <a href="">
                <img src="/images/global/email.svg" class="img-footer">
            </a>
            <label class="label-footer">+55 (15) 5555-5555</label>
        </footer>

        <!--Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    </body>
</html>