<!doctype html>
<html lang="pt-br">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-requisicao-de-vaga.css">

    <title>Gerar Requisição de Vaga</title>

    <script type="text/javascript">
        let cargos = <?php echo json_encode($this -> view -> cargos) ?>;
    </script>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                <a class="nav-link" href="#">Home</a>
                    <a class="nav-link" href="#">Gestor</a>
                    <a class="nav-link active" href="#">Requisições</a>
                    <a class="nav-link" href="#">Vagas</a>
                    <a class="nav-link" href="#">Processos Seletivos</a>
                    <a class="nav-link" href="#">Sair</a>               
                </div>
            </div>
        </div>
    </nav>

    <!--body-->
    <form action="/gerar_vaga" method="post">
        <div class="container">

            <div class="title">
                <h1 class="title-1">Gerar Requisição de Vaga</h1>
            </div>

            <!--Dados de Solicitaçao-->
            <div class="title">
                <h2 class="title-2">Dados de Solicitação</h2>
                <img src="images/global/info.svg">
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label title-interview">Título da Vaga</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form1" id="colFormLabel" placeholder="" name="titulo_vaga">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="colsm-2 form-label">Requisitante</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control form1" id="colFormLabel" placeholder="" name="requisitante"
                        readonly>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Data de Solicitação</label>
                <div class="col-sm-10">
                    <input type="date" class="form-control form1" id="colFormLabel" placeholder=""
                        name="data_solicitacao">
                </div>
            </div>

            <!--Dados de Vaga-->
            <div class="title">
                <h2 class="title-2">Dados de Vaga</h2>
                <img src="/images/global/info.svg">
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Departamento</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="departamento" onchange="atribuitDept(this)">
                        <option selected>--Selecione--</option>
                        <?php foreach ($this->view->departamentos as $key => $departamento) { ?>
                        <option value="<?=$departamento->id_departamento?>">
                            <?= $departamento->nome_departamento ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Cargo</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" name="cargo">
                        <option selected>--Selecione--</option>
                        <?php foreach ($this->view->cargos as $key => $cargo) { ?>
                        <option value="<?=$cargo->id_cargo?>">
                            <?= $cargo->nome_cargo ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Vínculo Empregatício</label>
                <div class="col-sm-10">
                    <select class="col form-select form1" aria-label="Formação" name="vinculo_empregaticio">
                        <option selected>--Selecione--</option>
                        <option value="1">CLT</option>
                        <option value="2">PJ</option>
                        <option value="3">Estágio</option>
                    </select>
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Salário</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form1" id="colFormLabel" placeholder="" name="salario"
                        min="0">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Horário de Trabalho</label>
                <div class="col-sm-10 input-1">
                    <input type="time" class="form-control form2" id="colFormLabel" placeholder=""
                        name="hora_trab_inicio">
                </div>
                <label for="colFormLabel" class="col label-middle">à</label>
                <div class="col-sm-10 input-2">
                    <input type="time" class="form-control form2" id="colFormLabel" placeholder="" name="hora_trab_fim">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Número de Vagas</label>
                <div class="col-sm-10">
                    <input type="number" class="form-control form1" id="colFormLabel" placeholder="" name="numero_vagas"
                        min="0">
                </div>
            </div>

            <div class="row mb-3">
                <label for="colFormLabel" class="col-sm-2 form-label">Função</label>
                <div class="col-sm-12 mb-3">
                    <textarea type="text" class="form-control" id="textarea" rows="3" name="funcao"></textarea>
                </div>
            </div>

            <!--Experiências-->
            <div class="title">
                <h2 class="title-2">Experiências</h2>
                <img src="/images/global/info.svg">
            </div>

            <div id="Exp">
                <div class="subtitle">
                    <h3 class="title-3">Experiência</h3>
                    <h3 class="numExp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-exp-formacao form3" aria-label="Experiência" name="exp-fomacao-1">
                        <option selected>Experiência</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>

                    <select class="col form-select cl-exp-status form3" aria-label="Status" name="exp-status-1">
                        <option selected>Status</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>

                <div class="row">
                    <label for="colFormLabel" class="col-sm-2 form-label exp-label">Anos de Experiência:</label>
                    <div class="col number">
                        <input type="number" class="form-control cl-exp-anos-experiencia form2" id="colFormLabel"
                            placeholder="00" name="exp-anos-experiencia-1">
                    </div>
                </div>

                <div id="btn-area-0" class="btn-area-exp">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addExp()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeExp()">
                </div>
            </div>

            <!--Competências-->
            <div class="title">
                <h2 class="title-2">Competências</h2>
                <img src="/images/global/info.svg">
            </div>

            <div id="Comp">
                <div class="subtitle">
                    <h3 class="title-3">Competência</h3>
                    <h3 class="numComp">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-comp-nome form3" aria-label="Nome" name="comp-nome-1">
                        <option selected>Nome</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>

                    <select class="col form-select cl-comp-grau form3" aria-label="Grau" name="comp-grau-1">
                        <option selected>Grau</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-comp-status form4" aria-label="Status" name="comp-status-1">
                        <option selected>Status</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>

                <div id="btn-area-comp-0" class="btn-area-comp">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addComp()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeComp()">
                </div>
            </div>

            <!--Formações-->
            <div class="title">
                <h2 class="title-2">Formações</h2>
                <img src="/images/global/info.svg">
            </div>

            <div id="Form">
                <div class="subtitle">
                    <h3 class="title-3">Formação</h3>
                    <h3 class="numForm">1</h3>
                </div>

                <div class="row mb-3">
                    <select class="col form-select cl-form-tipo form3" aria-label="Tipo" name="form-tipo-1">
                        <option selected>Tipo</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>

                    <select class="col form-select cl-form-status form3" aria-label="Status" name="form-status-1">
                        <option selected>Status</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>

                <div class="row">
                    <select class="col form-select cl-form-nome form3" aria-label="Nome" name="form-nome-1">
                        <option selected>Nome</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>

                    <select class="col form-select cl-form-grau form3" aria-label="Grau" name="form-grau-1">
                        <option selected>Grau</option>
                        <option value="1">#</option>
                        <option value="2">#</option>
                        <option value="3">#</option>
                    </select>
                </div>

                <div id="btn-area-form-0" class="btn-area-form">
                    <img src="/images/custom-requisicao-de-vaga/plus.svg" class="btn-form" onclick="addForm()">
                    <img src="/images/custom-requisicao-de-vaga/minus.svg" class="btn-form" onclick="removeForm()">
                </div>
            </div>

            <div class="buttons">
                <button type="button" class="btn btn-outline-primary mb-5">Voltar</button>
                <button type="submit" class="btn btn-outline-primary mb-5">Gerar</button>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/manager-scripts/gerar-requisicao-de-vaga.js"></script>
</body>

</html>