<!doctype html>
<html lang="pt-BR">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap / CSS -->
    <link rel="stylesheet" href="/styles/custom-home.css">

    <title>Home</title>
</head>

<body>
    <!--Header-->
    <nav class="navbar navbar-expand-lg navbar-dark" id="header">
        <div class="container-fluid background-navbar">
            <a class="navbar-brand" href="#"><img src="/images/global/logo.svg" alt=""></a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
                <img src="/images/global/navbar-button.svg" class="navbar-button">
            </button>

            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                    <a class="nav-link" href="#">Entrar</a>
                    <a class="nav-link" href="#scroll-1">Sobre</a>
                    <a class="nav-link" href="#scroll-2">Quem Somos</a>
                    <a class="nav-link" href="#scroll-3">Nossos Líderes</a>
                    <a class="nav-link" href="#scroll-4">Trabalhe Conosco</a>
                    <a class="nav-link" href="#scroll-5">Contato</a>
                </div>
            </div>
        </div>
    </nav>

    <!--Body-->
    <form action="requisitante.php" method="post">
        <div class="container">
            <!--slider-->
            <div class="slide-area">
                <div class="slider-home">
                    <div class="slides">
                        <!--radio buttons-->
                        <input type="radio" name="radio-btn" id="radio1">
                        <input type="radio" name="radio-btn" id="radio2">
                        <input type="radio" name="radio-btn" id="radio3">
                        <input type="radio" name="radio-btn" id="radio4">

                        <!--slide images-->
                        <div class="slide first">
                            <img src="/images/home/company.png" alt="">
                        </div>
                        <div class="slide">
                            <img src="/images/home/house.png" alt="">
                        </div>
                        <div class="slide">
                            <img src="/images/home/quality.png" alt="">
                        </div>
                        <div class="slide">
                            <img src="/images/home/work-with-us.png" alt="">
                        </div>
                    </div>

                    <!--automatic navigation-->
                    <div class="navigation-auto">
                        <div class="auto-btn1"></div>
                        <div class="auto-btn2"></div>
                        <div class="auto-btn3"></div>
                        <div class="auto-btn4"></div>
                    </div>

                    <!--manual navigation-->
                    <div class="navigation-manual">
                        <label for="radio1" class="manual-btn" onclick="setCounter(this)" id="btn1"></label>
                        <label for="radio2" class="manual-btn" onclick="setCounter(this)" id="btn2"></label>
                        <label for="radio3" class="manual-btn" onclick="setCounter(this)" id="btn3"></label>
                        <label for="radio4" class="manual-btn" onclick="setCounter(this)" id="btn4"></label>
                    </div>
                </div>
            </div>

            <!--Sobre nós-->
            <div class="about-area">
                <div id="scroll-1"></div>
                <div class="card-about">
                    <div class="icon-about-area">
                        <img class="icon-about" src="/images/home/eletron.svg">
                    </div>

                    <div class="title-about-area">
                        <h1 class="title">
                            Mogetec
                        </h1>
                    </div>

                    <div class="text-about-area">
                        <p class="text-about">
                            Nós somos uma empresa de engenharia elétrica especializada na ampla gama de serviços
                            elétricos, abrangendo estudos, laudos, medições e instalações elétricas.
                        </p>
                        <p class="text-about">
                            Valorizamos a competência técnica e a inovação tecnológica para ambientes cada vez mais
                            sofisticados.
                        </p>
                        <p class="text-about">
                            Acompanhamos todas as nossas obras de perto, para garantir o cumprimento do cronograma,
                            prazo e acabamentos.
                        </p>
                    </div>
                </div>
            </div>

            <!--quem somos-->
            <div class="dark-area">
                <div id="scroll-2"></div>
                <div class="dark-block">
                    <h1 class="quem-somos-title">Quem Somos?</h1>

                    <div class="quem-somos-area">
                        <img class="quem-somos-img" src="/images/home/quem-somos.jpg">

                        <p class="text-quem-somos">Nossa empresa foi fundada em Agosto de 2005. Iniciamos nossas
                            atividades focadas no ramo de manutenções elétricas empresariais, após alguns anos,
                            adquirindo
                            conhecimento e especialização, iniciamos nossas reformas residenciais e
                            comerciais de alto padrão.
                            Todas nossas obras são acompanhadas por responsáveis pelas normas, prazos e
                            segurança.
                        </p>
                    </div>
                </div>
            </div>

            <!--Cards-->
            <div class="card-area">
                <div class="card">
                    <div class="icon-card-area">
                        <img class="icon-card" src="/images/home/ethic.svg">
                    </div>

                    <div class="title-card-area">
                        <h1 class="title-card">
                            Ética e Respeito
                        </h1>
                    </div>

                    <div class="text-card-area">
                        <p class="text-card">
                            O Código de Ética reflete os princípios de nossa empresa e confirma
                            nosso compromisso de agir de forma respeitosa em todas as relações com
                            colaboradores e terceiros.
                        </p>
                    </div>
                </div>

                <div class="card">
                    <div class="icon-card-area">
                        <img class="icon-card" src="/images/home/tech.svg">
                    </div>

                    <div class="title-card-area">
                        <h1 class="title-card">
                            Tecnologia
                        </h1>
                    </div>

                    <div class="text-card-area">
                        <p class="text-card">
                            Usamos a Tecnologia como nossa principal forma de ver o mundo. Procuramos sempre utilizar
                            tudo que há de novo no mercado, prezando sempre pela inovação e modernidade.
                        </p>
                    </div>
                </div>

                <div class="card">
                    <div class="icon-card-area">
                        <img class="icon-card" src="/images/home/quality.svg">
                    </div>

                    <div class="title-card-area">
                        <h1 class="title-card">
                            Qualidade
                        </h1>
                    </div>

                    <div class="text-card-area">
                        <p class="text-card">
                            Buscamos a conformidade consistente com as expectativas dos clientes e às normas
                            estabelecidas. Adequando nosso trabalho para a finalidade de seguir o que foi projetado.
                        </p>
                    </div>
                </div>
            </div>

            <!--Teams-->
            <div class="team-area">
                <div id="scroll-3"></div>
                <h1 class="lideres-title">Nossos Líderes</h1>
                <div class="team-section">
                    <div class="person">
                        <img src="/images/home/leader-engineering.svg" alt="" class="person-pic">

                        <div class="person-info">
                            <h2>Emanuel Leandro</h2>
                            <p>Engenharia Elétrica</p>
                        </div>
                    </div>

                    <div class="person">
                        <img src="/images/home/leader-customer.svg" alt="" class="person-pic">

                        <div class="person-info">
                            <h2>Thiago Porto</h2>
                            <p>Atendimento ao Cliente</p>
                        </div>
                    </div>

                    <div class="person">
                        <img src="/images/home/leader-design.svg" alt="" class="person-pic">

                        <div class="person-info">
                            <h2>Rebeca Carvalho</h2>
                            <p>Design de Interiores</p>
                        </div>
                    </div>

                    <div class="person">
                        <img src="/images/home/leader-marketing.svg" alt="" class="person-pic">

                        <div class="person-info">
                            <h2>Clarice Vitória</h2>
                            <p>Marketing</p>
                        </div>
                    </div>
                </div>
            </div>

            <!--Vagas-->
            <div class="job-area" id="jobs">
                <div id="scroll-4"></div>
                <h1 class="title-job">Vagas Disponíveis</h1>

                <div class="left-btn" onclick="preCard()"></div>
                <div class="right-btn" onclick="nextCard()"></div>

                <div class="carrousel">
                    <div class="card vaga" id="1">
                        <div class="title-card-area">
                            <h1 class="title-card" id="">
                                Engenheiro Elétrico Júnior 1
                            </h1>
                        </div>

                        <div class="text-card-area">
                            <p class="text-card">
                                Sorocaba - SP
                            </p>
                        </div>

                        <div class="text-card-area">
                            <p class="text-card">Salário: <label>R$ X</label></p>
                        </div>

                        <div class="text-card-area">
                            <p class="text-card">Vagas Abertas: <label>X</label></p>
                        </div>

                        <button class="btn-view-job">Visualizar</button>
                    </div>
                </div>
            </div>

            <!--Contact us-->
            <div class="contact-area">
                <div id="scroll-5"></div>
                <h1 class="title-contact">Contate-nos</h1>

                <div class="contact-section">
                    <form action="#">
                        <div class="inputs">
                            <div class="form-row">
                                <div class="input-data">
                                    <input type="text" required>
                                    <div class="underline"></div>
                                    <label>Primeiro Nome</label>
                                </div>

                                <div class="input-data">
                                    <input type="text" required>
                                    <div class="underline"></div>
                                    <label>Último Nome</label>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="input-data">
                                    <input type="email" id="email" onmouseout="verificar()" required>
                                    <div class="underline"></div>
                                    <label id="label-email">E-mail</label>
                                </div>

                                <div class="input-data">
                                    <input type="text" required>
                                    <div class="underline"></div>
                                    <label>Assunto</label>
                                </div>
                            </div>

                            <div class="form-row text-area">
                                <div class="input-data textarea">
                                    <textarea cols="30" rows="10" required></textarea>
                                    <div class="underline"></div>
                                    <label>Escreva sua mensagem</label>
                                </div>
                            </div>

                            <div class="form-row submit-btn">
                                <div class="input-data">
                                    <div class="inner"></div>
                                    <input type="submit" value="enviar">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </form>

    <!--Footer-->
    <footer class="footer">
        <img src="/images/global/linkedin.svg" class="img-footer" onclick="">
        <img src="/images/global/facebook.svg" class="img-footer" onclick="">
        <img src="/images/global/email.svg" class="img-footer" onclick="">
        <label class="label-footer">+55 (15) 5555-5555</label>
    </footer>

    <!--Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ"
        crossorigin="anonymous"></script>

    <script src="/scripts/general-scripts/home.js"></script>
</body>

</html>